# Generated by Django 5.2.16 on 2026-07-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaValidationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_idea', models.TextField()),
                ('target_audience', models.TextField()),
                ('budget', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_data', models.JSONField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
